# Generated by Django 5.0.7 on 2024-07-30 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="units",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_units", models.IntegerField()),
                ("unit_type", models.CharField(max_length=100)),
                ("floor", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.datetime.now)),
                ("customer_num", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
                ("birthday", models.CharField(max_length=100)),
                ("national_id", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("mobile", models.CharField(max_length=50)),
                ("occupation", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("clientSource", models.CharField(max_length=50)),
                ("broker_company", models.CharField(max_length=50)),
                ("dev_sales", models.CharField(max_length=50)),
                ("broker_sales", models.CharField(max_length=50)),
                ("dev_sales_manager", models.CharField(max_length=50)),
                ("units", models.ManyToManyField(to="home.units")),
            ],
        ),
    ]
