# Generated by Django 5.0.7 on 2024-07-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customers_num",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_num", models.IntegerField(default=1000)),
            ],
        ),
        migrations.AlterModelOptions(
            name="orders",
            options={"ordering": ["customer_num"]},
        ),
    ]
