# Generated by Django 5.0.7 on 2024-07-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_customers_num_alter_orders_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="branch",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
