# Generated by Django 5.0.7 on 2024-07-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_units_num_customers_num_sympol_orders_broker_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="customer_num",
            field=models.CharField(default="G1002", max_length=50),
        ),
        migrations.AlterField(
            model_name="units",
            name="number_of_units",
            field=models.CharField(default="EOI1003", max_length=50),
        ),
    ]
