# Generated by Django 5.0.7 on 2024-07-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_orders_customer_num_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Thraa_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("broker_company", models.CharField(max_length=10000)),
                ("dev_sale", models.CharField(max_length=10000)),
                ("dev_sale_manager", models.CharField(max_length=10000)),
            ],
        ),
    ]
