# Generated by Django 5.0.7 on 2024-07-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_thraa_info_broker_company_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="broker_company_id",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
