# Generated by Django 5.0.7 on 2024-08-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_alter_orders_broker_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="ambassador_email",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="ambassador_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="ambassador_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="ambassador_phone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
