# Generated by Django 5.0.7 on 2024-08-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_orders_ambassador_email_orders_ambassador_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thraa_info",
            name="broker_company",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="thraa_info",
            name="broker_company_id",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="thraa_info",
            name="dev_sale",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="thraa_info",
            name="dev_sale_manager",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
