# Generated by Django 5.0.7 on 2024-08-01 03:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_alter_thraa_info_broker_company_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="thraa_info",
            options={"ordering": ["-id"]},
        ),
    ]
