# Generated by Django 5.0.7 on 2024-08-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_alter_thraa_info_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="amount",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
