# Generated by Django 5.0.7 on 2024-08-01 04:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_orders_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="thraa_info",
            options={
                "ordering": ["id"],
                "verbose_name": "Borkers_info",
                "verbose_name_plural": "Borkers_info",
            },
        ),
    ]
