# Generated by Django 5.0.7 on 2024-08-01 04:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_alter_thraa_info_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="units_num",
            options={"verbose_name": "EOI Number", "verbose_name_plural": "EOI Number"},
        ),
    ]
