# Generated by Django 5.0.7 on 2024-08-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0016_alter_units_num_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="payment_method",
            field=models.CharField(
                blank=True, default="cash", max_length=100, null=True
            ),
        ),
    ]
