# Generated by Django 5.0.7 on 2024-08-04 19:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0017_orders_payment_method"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="units_num",
            options={
                "ordering": ["-uints_num"],
                "verbose_name": "EOI Number",
                "verbose_name_plural": "EOI Number",
            },
        ),
    ]
