# Generated by Django 5.0.7 on 2024-08-04 19:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0019_alter_units_num_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="units_num",
            options={
                "ordering": ["-id"],
                "verbose_name": "EOI Number",
                "verbose_name_plural": "EOI Number",
            },
        ),
    ]
